# Generated by Django 2.2.5 on 2020-06-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gdt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('mn', models.CharField(max_length=10)),
                ('rno', models.IntegerField()),
                ('gemail', models.EmailField(max_length=100)),
                ('gdate', models.CharField(max_length=100)),
                ('gtime', models.CharField(max_length=100)),
                ('passs', models.CharField(max_length=100)),
                ('cpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=100)),
                ('ef', models.CharField(max_length=100)),
                ('co', models.CharField(max_length=100)),
                ('rt', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminnotice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pptt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('mn', models.CharField(max_length=10)),
                ('rno', models.IntegerField()),
                ('pdate', models.CharField(max_length=100)),
                ('pemail', models.EmailField(max_length=100)),
                ('ptime', models.CharField(max_length=100)),
                ('ppttopic', models.CharField(max_length=100)),
                ('passs', models.CharField(max_length=100)),
                ('cpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('mn', models.CharField(max_length=10)),
                ('rno', models.IntegerField()),
                ('remail', models.EmailField(max_length=100)),
                ('passs', models.CharField(max_length=100)),
                ('cpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
